name: Deploy do Projeto (Manual)

on:
  # Permite que vocÃª execute este workflow manualmente na interface do GitHub.
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag da Imagem (ex: 1.0.0 ou latest)'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Criar pasta do projeto no servidor
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.CLIENT_HOST }}
          username: ${{ secrets.CLIENT_USER  }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /opt/wamiddleware

      - name: Enviar arquivos para VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.CLIENT_HOST }}
          username: ${{ secrets.CLIENT_USER  }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/opt/wamiddleware"
          overwrite: true
          rsync: true
          rsync_args: "--exclude='.git' --exclude='node_modules'"
    
      - name: Criar .env
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.CLIENT_HOST }}
          username: ${{ secrets.CLIENT_USER  }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/wamiddleware
            echo "${{ secrets.DOT_ENV }}" > .env

      - name: Executar no servidor
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.CLIENT_HOST }}
          username: ${{ secrets.CLIENT_USER  }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR="/root/.nvm"
            source "$NVM_DIR/nvm.sh"

            cd /opt/wamiddleware

            npm install pm2 -g
            npm install
            npx patch-package
            npm run build
            pm2 start ./src/main.js
            pm2 list
